"""
Deterministic Risk Scoring Engine.

This module computes a deterministic risk score based on the Stage 2 fixed signals.
It ensures the base score is reproducible, auditable, and not generated by an LLM.

Weights and thresholds are fixed constants:
- BASE_SCORE = 100 (lowest risk)
- SEVERITY_WEIGHT: Base penalty multiplier per severity level.
- CHECK_WEIGHT: Importance multiplier per specific check.
"""
from typing import Dict, Any, List

BASE_SCORE = 100

# Base penalty by severity.
SEVERITY_WEIGHT = {
    "low": 5,
    "medium": 15,
    "high": 30
}

# Importance multiplier per check type.
# e.g., GSTIN mismatches are legally very significant (1.5x)
CHECK_WEIGHT = {
    "entity_consistency": 1.5,
    "benfords_law": 1.0,
    "transaction_velocity": 1.0,
    "threshold_anomaly": 1.0
}


def _extract_reason(check_name: str, check_data: dict) -> str:
    """Extract a human-readable reason directly from the deterministic signal data."""
    if check_name == "entity_consistency":
        mismatches = check_data.get("mismatches", [])
        if mismatches:
            m = mismatches[0]
            return f"Mismatch on {m.get('field')} between {m.get('document_a')} and {m.get('document_b')}"
        return "Entity inconsistency detected."
    elif check_name == "benfords_law":
        return f"Chi-square value {check_data.get('chi_square', 0)} exceeds threshold {check_data.get('threshold', 0)}."
    elif check_name == "transaction_velocity":
        return f"High velocity: {check_data.get('max_burst_count', 0)} transactions in {check_data.get('window_days', 0)} days."
    elif check_name == "threshold_anomaly":
        return f"MAD outlier detected: {check_data.get('max_outlier_amount', 0)} with Z-score {check_data.get('max_z_score', 0)}."
    
    return f"Anomaly flagged by {check_name}."


def compute_score(signals: Dict[str, Any]) -> Dict[str, Any]:
    """
    Computes the deterministic score and breakdown.
    `signals` is the dictionary of results from the signal layer.
    """
    deductions: List[Dict[str, Any]] = []
    total_penalty = 0

    for check_name, check_data in signals.items():
        if check_data.get("flagged"):
            severity = check_data.get("severity", "low")
            
            # Calculate penalty
            base_penalty = SEVERITY_WEIGHT.get(severity, 5)
            weight = CHECK_WEIGHT.get(check_name, 1.0)
            penalty = int(base_penalty * weight)
            
            total_penalty += penalty
            reason = _extract_reason(check_name, check_data)
            
            deductions.append({
                "check": check_name,
                "severity": severity,
                "penalty": penalty,
                "reason": reason
            })

    # Clamp score to [0, 100]
    algorithmic_score = max(0, BASE_SCORE - total_penalty)

    return {
        "base_score": BASE_SCORE,
        "deductions": deductions,
        "algorithmic_score": algorithmic_score
    }


def determine_confidence_and_action(final_score: int) -> Dict[str, str]:
    """
    Determines confidence and recommended action based on fixed score thresholds.
    """
    if final_score >= 80:
        return {"confidence": "high", "recommended_action": "approve"}
    elif final_score >= 50:
        return {"confidence": "moderate", "recommended_action": "human_review"}
    else:
        # Score < 50
        return {"confidence": "high", "recommended_action": "escalate"}
