import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';

import 'theme/app_theme.dart';
import 'providers/auth_provider.dart';
import 'providers/case_provider.dart';
import 'services/notification_service.dart';
import 'services/api_service.dart';

import 'screens/login_screen.dart';
import 'screens/sme/sme_home_screen.dart';
import 'screens/officer/officer_home_screen.dart';
import 'firebase_options.dart'; // Will be generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase (wrapped in try-catch in case flutterfire configure wasn't run yet)
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint("Firebase init failed (did you run flutterfire configure?): $e");
  }
  
  // Initialize notification service (FCM stub)
  await NotificationService().initialize();

  runApp(
    MultiProvider(
      providers: [
        Provider(create: (_) => ApiService()),
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => CaseProvider()),
      ],
      child: const AuditGemmaApp(),
    ),
  );
}

class AuditGemmaApp extends StatelessWidget {
  const AuditGemmaApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'AuditGemma',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.darkTheme,
      home: Consumer<AuthProvider>(
        builder: (context, auth, _) {
          if (!auth.isLoggedIn) {
            return const LoginScreen();
          }
          if (auth.isSme) {
            return const SmeHomeScreen();
          }
          return const OfficerHomeScreen();
        },
      ),
    );
  }
}

